locales:
  tqn:
    name: Sahaptin Tenino Keyboards
    description: >-
      Mobile OS keyboards for the Sahaptin Tenino language from the Divvun group
      at UiT.
  en:
    name: Sahaptin Tenino Keyboards
    description: >-
      Mobile OS keyboards for the Sahaptin Tenino language from the Divvun group
      at UiT.
  nb:
    name: Sahaptin Tenino tastatur
    description: Mobiltastatur for Sahaptin Tenino fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
